filebeat.inputs:
- type: log
  paths:
    - /var/log/plc/*
  json:
    key_under_root: true

output.elasticsearch:
  hosts: ["http://192.168.80.3:9200"]
  index: "plc-%{[agent.version]}-%{+yyyy.MM.dd}"

setup.template:
  name: "plc"
  pattern: "plc-*"
